### ISSUE TITLE
Vite & monaco-editor-workers

### ISSUE THREAD

**Issue by cdietrich** [TypeFox/monaco-components#67]
Hi, how to bundle monaco-editor-workers with vite? is there any example that works with import meta url?

**Comment by cdietrich** [comment]
monaco seeems to whine if there is no worker.

**Comment by kaisalmen** [comment]
Yes, it likes the editor to be in a worker. I will work on the bespoke issue above today and move this topic forward along

**Comment by kaisalmen** [comment]
@cdietrich new preview release contain the new implementation, they are listed here: https://github.com/TypeFox/monaco-languageclient/pull/600#issue-2106106992

It is more versatile, because you have various possibilities to configure or overwrite it. Here are example how to use it.

Use pre-bundled version;
https://github.com/TypeFox/monaco-languageclient/blob/merge-monaco-edtior-wrapper/packages/examples/src/python/client/reactPython.tsx#L12-L16

Provide your own (compatible with vite and webpack):
https://github.com/TypeFox/monaco-languageclient/blob/merge-monaco-edtior-wrapper/packages/examples/src/json/client/wrapperWs.ts

**Comment by kaisalmen** [comment]
vite and webpack need to understand the `new Worker(...)` call. If you "hide" it in configuration, they are not able to extract the workers, that is the reason the second example defined a such. The pre-bundles are well suited for pure HTML+JS or Angular.

**Comment by cdietrich** [comment]
@kaisalmen is there a sample of a dependency list that works together? the like of 
 ```
    "@codingame/monaco-vscode-configuration-service-override": "~1.85.0",
    "@codingame/monaco-vscode-editor-service-override": "~1.85.0",
    "@codingame/monaco-vscode-files-service-override": "~1.85.0",
    "@typefox/monaco-editor-react": "^2.6.0",
    "monaco-editor": "npm:@codingame/monaco-editor-treemended@>=1.85.0 <1.86.0",
    "monaco-languageclient": "~7.3.0",
    "monaco-editor-workers": "^0.45.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "vscode": "npm:@codingame/monaco-vscode-api@>=1.85.0 <1.86.0"
    ```

**Comment by kaisalmen** [comment]
@cdietrich Regarding ⬆️ sorry, I have not received a notification or overlooked it.

**Comment by kaisalmen** [comment]
`@codingame/monaco-editor-treemended` => `@codingame/monaco-vscode-editor-api`

**Comment by cdietrich** [comment]
@kaisalmen  hmmmm still have problems to get this running

✘ [ERROR] No matching export in "node_modules/monaco-editor/api.js" for import "editor"

    node_modules/monaco-editor-wrapper/dist/editorAppClassic.js:5:9:
      5 │ import { editor, languages } from 'monaco-editor';

**Comment by kaisalmen** [comment]
@cdietrich did you define it like this in the package.json?
```
"monaco-editor": "npm:@codingame/monaco-vscode-editor-api@~3.1.2"
```
